name: Tag Docker Image on Push using github shared workflow

on:
  push:
    branches:
      - develop
      - main

jobs:
  tag-staging:
    if: ${{ github.ref_name == 'develop' }}
    uses: amandhal/workflow-repository/.github/workflows/docker-ci.yml@v1.0.0
    with:
      image_name: frontend
      source_tag: latest
      target_tag: staging-${{ github.sha }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  tag-prod:
    if: ${{ github.ref_name == 'main' }}
    uses: amandhal/workflow-repository/.github/workflows/docker-ci.yml@v1.0.0
    with:
      image_name: frontend
      source_tag: latest
      target_tag: prod-${{ github.run_number }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
